name: Setup project
description: Prepare the project for any CI action

inputs:
  node-version:
    description: Version of Node to install
    default: 22

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 📦 Install dependencies
      run: yarn install --immutable
      shell: bash
